### ISSUE TITLE
Test script doesn't work as expected

### ISSUE THREAD

**Issue by berzanorg** [nicoeft/doors-vs-wheels#1]
Hey! I was reading your tutorial at Medium and writing my Solana program. I've finished building but the test script didn't work as I expected. Then, I've checked my code to find any error but I couldn't be able to find. So, I've copied and pasted the contents of your lib.rs and doors-vs-wheels.ts files, and tested again, but it didn't work, too. I wonder if there is an API change. The first error message is below, all other errors are related to it: 

```
1)  doors-vs-wheels
        Base user: Initialize OK - counter with 0 votes for doors and wheels:
     Error: Invalid arguments: votesCounter not provided.
```

Note: The doors-vs-wheels website is working. The only issue is about the test script.
Thank you for the great tutorial.
~ Berzan

**Comment by nicoeft** [comment]
Hi! Thank you for going through it I'm glad you found it helpful.

Regarding this issue, It seems it's because of the Anchor.toml settings. Since version 0.24 programs can infer PDAs without the need of explicitly passing them, but you need to set 'seed' to true in features enable this.


```
[features]  
seeds = true
```


If the error persists, tell me and I'll do some debugging.

**Comment by berzanorg** [comment]
Thank you! It works like a charm.
